# @name updateDocument
PUT {{SERVICE_B_HOST}}/v1/documents/remote/b55ca251-1080-48cf-87ee-7ab7de218e37
Content-Type: application/json
Authorization: Basic alongi@email.com:12345678

{
    "title": "130 in autostrada"
}
